version: "3.8"

services: 
    backend:
        env_file:
            "./backend/.env"
        build: 
            context: ./backend
            dockerfile: ./Dockerfile
        container_name: doc_container_2
        # image: "doc_container_2"
        ports: 
            - "5000:5000"
        depends_on: 
            - mysql_server
        
    mysql_server:
        image: mysql:5.7.24
        environment: 
            - MYSQL_DATABASE=oncaredb
            - MYSQL_ROOT_USER=root
            - MYSQL_ROOT_PASSWORD=mysqlpass11233
            - MYSQL_PASSWORD=mysqlpass11233
        ports:
            - "3306:3306"

    frontend:
        build:
            context: ./frontend/oncare
            dockerfile: ./Dockerfile
        container_name: doc_container_1
        # image: "doc_container_1"
        ports: 
            - "3000:3000"
